const TEXT_ALIGNMENT_START  = 'start';
const TEXT_ALIGNMENT_MIDDLE = 'middle';
const TEXT_ALIGNMENT_END    = 'end';

const CONSTRUCTOR_HANDLE_ROTATE     = 1;
const CONSTRUCTOR_HANDLE_REMOVE     = 2;
const CONSTRUCTOR_HANDLE_SCALE      = 3;

export const TEXT_ALIGNMENT = {
    START:  TEXT_ALIGNMENT_START,
    MIDDLE: TEXT_ALIGNMENT_MIDDLE,
    END:    TEXT_ALIGNMENT_END
};
export const CONSTRUCTOR_HANDLES = {
    ROTATE: CONSTRUCTOR_HANDLE_ROTATE,
    REMOVE: CONSTRUCTOR_HANDLE_REMOVE,
    SCALE:  CONSTRUCTOR_HANDLE_SCALE
};